- hosts: localhost
  connection: local
  become: true 

  tasks: 
  - name: Install htop
    apt:
      name: htop
  tasks:
  - name:  Install nginx
    apt:
      name: nginx

  - name: Install VLC
      apt:
        name: vlc
        state: present
        update_cache: yes
